# -*- coding: utf-8 -*-
"""Taller 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZvYJUpyJbNqwKzj_gtmnfZ4xIp2gABY0

#Taller 2
#Grupo_3
#Integrantes: Andres Solano, Mary Ortiz, Jesús Rios y Juan Sebastian Manrique

1. *Escriba* un algoritmo que dado un número entero, indique si este valor es par o impar.(recordar Todos los operadores aritméticos [+, -, *, /, %MOD])
"""

#inicio
N=int(input("Escribe un numero"))#Variable de ingreso
Residuo=N%2#Operación para determinar el residuo de la variable
if Residuo==0:#Condición para determinar si la variable es par o inpar
  print("Su número es par")
else:#Negación de la condición
  print("Su número es impar")

"""Escriba un algoritmo que pida un número y también un porcentaje entre 0 y 100 que puede ser decimal,  el algoritmo debe entregar el cálculo del porcentaje del primer número, Si el usuario ingresa un dato fuera del rango  (0 a 100), debe mostrar un error y volver a pedir el porcentaje.

"""

#inicio
N=float(input("Escribe un numero" )) #variable de ingreso numero
P=float(input("Escribe un porcentaje" )) #variable de ingreso porcentaje
Pp=(N * P)/100 #como hallar el porcentaje
while P>100:#bucle hasta que el porcentaje sea menor a 100
  print("ERROR!!")#resultado condicion verdadera
  P=float(input("Escribe un porcentaje valido"))#reingreso variable invalida
if P<=100: #condicion porcentaje mayor a 100
  print((N * P)/100)#resultado variable valida
else:#negacion condicion
  print(Pp)#resultado condicion falsa

"""3.Con base en el primer Ejercicio, si el número indicado es par, entregar todos los números pares entre el 0 y el número."""

#Inicio
n=int(input("Dijite el número:"))#variable de ingreso
if (n%2)==0 :#condición para hallar el número par 
  print("El número",n,"es par")#Resultado cuando la condición es verdadera
  for a in range(0,n) :#indica el rango de los números menores al número par
    if (a%2)==0 :#condición para imprimir los numeros pares menores de n
      print("Los números pares menores a",n,"son:",a,)#Imprime los números pares menores a n
else :  #Negación de la condición
 print("El número",n,"es impar")#Resultado que tiene la negación de la condición

"""4.Escriba un algoritmo que dado un número entero, entregue la suma de todos los números entre el 0 y el número dado."""

#Inicio
z=int(input("Escriba un número entero:"))#variable de ingreso
print("El número entero es: ",z,)#Impresión de la variable
for a in range(0,z+1) :#indica el rango de los números menores al número par
    print("Los números entre 0 y",z,"son:",a,)#Números del rango
print("La suma de los números entre 0 y",z,"es:",sum(range(0,z+1)),)#Resultado de la sumatoria de los números de 0 al número escrito